services:
  front-end:
    build: client-pwa
    ports:
      - "8080:80"
  
  back-end:
    build: server
    ports:
      - "3000:3000"
    environment:
      API_KEY: $API_KEY
    
  proxy:
    build: proxy
    ports: 
      - "80:80"
    extra_hosts:
      weather.shurms.com: "127.0.0.1"
      weather-api.shurms.com: "127.0.0.1"

