export const weatherSites = {
    Locations: {
        Location: [
            {
                elevation: '7.0',
                id: '3066',
                latitude: '57.6494',
                longitude: '-3.5606',
                name: 'Kinloss',
                region: 'gr',
                unitaryAuthArea: 'Moray',
            },
            {
                elevation: '6.0',
                id: '3068',
                latitude: '57.712',
                longitude: '-3.322',
                obsSource: 'LNDSYN',
                name: 'Lossiemouth',
                region: 'gr',
                unitaryAuthArea: 'Moray',
            },
            {
                elevation: '36.0',
                id: '3075',
                latitude: '58.454',
                longitude: '-3.089',
                obsSource: 'LNDSYN',
                name: 'Wick John O Groats Airport',
                region: 'he',
                unitaryAuthArea: 'Highland',
            },
            {
                elevation: '15.0',
                id: '3002',
                latitude: '60.749',
                longitude: '-0.854',
                name: 'Baltasound',
                region: 'os',
                unitaryAuthArea: 'Shetland Islands',
            },
            {
                elevation: '89.0',
                id: '99057',
                latitude: '52.017',
                longitude: '-0.6',
                name: 'Woburn',
                region: 'ee',
                unitaryAuthArea: 'Central Bedfordshire',
            },
            {
                elevation: '170.0',
                id: '3781',
                latitude: '51.303',
                longitude: '-0.09',
                name: 'Kenley',
                region: 'se',
                unitaryAuthArea: 'Surrey',
            },
        ],
    },
};
