name: 🚀 ClientPWA
on:
  push:
    branches:
      - main
    paths:
      - 'client-pwa/**'
      - '.github/workflows/client-pwa.yaml'
  pull_request: {}

permissions:
    actions: write
    contents: read

jobs:
    verify:
        name: ⬣ Verify
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.5.0
                  cache: 'yarn'
                  cache-dependency-path: yarn.lock

            - name: Run install
              run: yarn install --frozen-lockfile

            - name: Run lint
              run: yarn lint

            - name: Run typecheck
              run: yarn typecheck

            - name: Run test
              run: yarn test:ci

    deploy:
        name: ⬣ Deploy
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.5.0
                  cache: 'yarn'
                  cache-dependency-path: yarn.lock

            - run: yarn install --frozen-lockfile
            - run: yarn build

            - name: deploy to s3
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-west-2
            - run: aws s3 sync ./dist s3://real-weather
